Repository SOPT-all/36-COLLABORATION-iOS-MCDONALDS, pull requests merged in 2025-05, with the labels that each got.

#5 [feat/#4] Base, Extension 추가
  MCDONALDS_iOS/MCDONALDS_iOS.xcodeproj/project.pbxproj
  MCDONALDS_iOS/MCDONALDS_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Base/BaseCollectionReusableView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Base/BaseCollectionViewCell.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Base/BaseView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Base/BaseViewController.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Extensions/.gitkeep
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Extensions/UILabel+.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Extensions/UIStackView+.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Extensions/UIView+.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Utils/.gitkeep
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Utils/ReuseIdentifiable.swift
Labels: 🍕 seungwon, ✨ feat, 🚑️ hotfix

#6 [add/#1] font, extension 추가
  MCDONALDS_iOS/MCDONALDS_iOS.xcodeproj/project.pbxproj
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Extensions/UIFont+.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Resources/Fonts/.gitkeep
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Resources/Fonts/Pretendard-Bold.otf
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Resources/Fonts/Pretendard-Medium.otf
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Resources/Fonts/Pretendard-Regular.otf
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Resources/Fonts/Pretendard-SemiBold.otf
  MCDONALDS_iOS/MCDONALDS_iOS/Info.plist
Labels: 🍟 sangyup, 💄 add

#11 [feat] 맥도날드 버튼 컴포넌트 구현
  MCDONALDS_iOS/MCDONALDS_iOS.xcodeproj/project.pbxproj
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Components/.gitkeep
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Components/McdonaldsButton.swift
Labels: 🍕 seungwon, ✨ feat

#12 [feat] 커스텀 네비게이션바 구현
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Base/BaseViewController.swift
Labels: 🍕 seungwon, ✨ feat

#14 [feat] 매장찾기 필터 버튼 및 지도 이미지뷰 구현
  MCDONALDS_iOS/MCDONALDS_iOS/Application/SceneDelegate.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Components/FilterButton.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Resources/Assets.xcassets/mapImage.imageset/Contents.json
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Resources/Assets.xcassets/mapImage.imageset/Image.png
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/FindStore/FindStoreView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/FindStore/FindStoreViewController.swift
Labels: 🍕 seungwon, ✨ feat

#16 [Feat/#7] 아코디언 메뉴 컴포넌트 구현
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Components/AccordionMenu/BeverageMenu/BeverageMenuView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Components/AccordionMenu/BeverageMenu/ExpandedBeverageMenuView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Components/AccordionMenu/BeverageMenu/ExpandedIceEAView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Components/AccordionMenu/BugerMenu/BurgerMenuView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Components/AccordionMenu/BugerMenu/ExpandedToppingEAView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Components/AccordionMenu/SideMenu/ExpandedEAView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Components/AccordionMenu/SideMenu/ExpandedSideMenuView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Components/AccordionMenu/SideMenu/SideMenuView.swift
Labels: 🍟 sangyup, ✨ feat

#23 [Feat/#17] 주문하기 뷰 구현
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Components/AccordionMenu/BeverageMenu/ExpandedIceEAView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Global/Components/AccordionMenu/SideMenu/ExpandedEAView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/Order/OrderView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/Order/OrderViewController.swift
Labels: 🍟 sangyup, ✨ feat

#24 [feat] 메뉴 리스트 컬렉션 뷰 & 주문하기 뷰 연결
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/MenuList/Cell/MenuListCollectionViewCell.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/MenuList/MenuListView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/MenuList/MenuListViewController.swift
Labels: 🍕 seungwon, ✨ feat

#25 ✨ Network Setting
  MCDONALDS_iOS/MCDONALDS_iOS.xcodeproj/project.pbxproj
  MCDONALDS_iOS/MCDONALDS_iOS/Info.plist
  MCDONALDS_iOS/MCDONALDS_iOS/Network/.gitkeep
  MCDONALDS_iOS/MCDONALDS_iOS/Network/Base/BaseResponseBody.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/Base/BaseService.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/Base/Environment.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/Base/ModelType.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/Base/NetworkError.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/Base/NetworkProvider.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/Base/TargetType.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/DTO/ResponseDTO/MenuListResponseDTO.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/Logger/NetworkLogger.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/Service/MenuService.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/TargetType/MenuTargetType.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/MenuList/MenuListViewController.swift
Labels: 🍕 seungwon, ✨ feat

#28 [feat] 메뉴 리스트 API 연결
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/MenuList/Cell/MenuListCollectionViewCell.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/MenuList/MenuListViewController.swift
Labels: 🍕 seungwon, ✨ feat

#32 [Feat/#26] 주문하기 뷰 네트워크 연동
  MCDONALDS_iOS/MCDONALDS_iOS/Network/DTO/RequestDTO/CartRequestDTO.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/DTO/ResponseDTO/MenuDetailResponseDTO.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/Service/CartService.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/Service/MenuService.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/TargetType/CartTargetType.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/TargetType/MenuTargetType.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/MenuList/MenuListViewController.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/Order/OrderView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/Order/OrderViewController.swift
Labels: 🍟 sangyup, ✨ feat

#37 [feat] 빈 주문내역 구현, api 연결
  MCDONALDS_iOS/MCDONALDS_iOS/Network/DTO/ResponseDTO/EmptyResponseDTO.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/Service/OrderService.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/TargetType/MenuTargetType.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Network/TargetType/OrderTargetType.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/OrderList/BottomSheetView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/OrderList/BottomSheetViewController.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/OrderList/OrderListView.swift
  MCDONALDS_iOS/MCDONALDS_iOS/Presentation/OrderList/OrderListViewController.swift
Labels: 🍕 seungwon, ✨ feat
